code_court/courthouse/views/defendant.py
import collections

from markdown import markdown
from enum import Enum

import util

import datetime

import model
from database import db_session

from flask_login import current_user
from flask import abort, Blueprint, current_app, render_template, request, Markup

defendant = Blueprint("defendant", __name__, template_folder="templates")


@defendant.route("/", methods=["GET"])
def index():
    """
    The index page for the defendant frontend

    Returns:
        a rendered defendant view template which shows all available problems
    """
    problems = model.Problem.query.all()

    return render_template("defendant/index.html", problems=problems)


RunState = Enum("RunState", "judging passed failed")


@defendant.route("/problem/<problem_id>/", methods=["GET"])
@defendant.route("/problem/<problem_id>/", methods=["POST"])
def problem(problem_id):
    problems = model.Problem.query.filter_by(id=problem_id).all()
    if len(problems) == 0:
        current_app.logger.info("Probelm %s doesn't exist", problem_id)
        abort(400)
    problem = problems[0]

    markdown_statement = Markup(markdown(problem.problem_statement))

    source_code = None
    if request.method == "POST":
        source_code = submit_code(problem)

    return render_template(
        "defendant/problem.html",
        problem=problem,
        markdown_statement=markdown_statement,
        source_code=source_code,
    )


@defendant.route("/submissions", methods=["GET"])
def submissions():
    submissions = model.Run.query.filter_by(
        user=current_user, is_submission=True
    ).order_by(
        model.Run.submit_time.desc()
    ).all()

    return render_template("defendant/submissions.html", submissions=submissions)


def submit_code(problem):
    """
    Creates a Run object and adds it to the database

    Args:
        problem: the problem source_code is being submitted to

    Returns:
        the submitted source_code as a string
    """
    source_code = request.form.get("source_code")
    if source_code is None:
        # TODO: give better feedback for failure
        current_app.logger.info("No source code given")
        abort(400)

    current_time = datetime.datetime.utcnow()

    # Hardcoded run details for the time being
    test_user = model.User.query.filter_by(username="testuser1").one()
    test_contest = model.Contest.query.filter_by(name="test_contest").one()
    python = model.Language.query.filter_by(name="python").one()

    button_action = request.form.get("action")
    is_submission = button_action == "submit" and not button_action == "run"

    run = model.Run(
        test_user,
        test_contest,
        python,
        problem,
        current_time,
        source_code,
        problem.secret_input,
        problem.secret_output,
        is_submission,
    )

    db_session.add(run)
    db_session.commit()

    return source_code

code_court/courthouse/views/main.py
from flask import Blueprint, send_from_directory

main = Blueprint("main", __name__, template_folder="templates")


@main.route("/flaskstatic/<path:path>")
def send_flask_static(path):
    return send_from_directory("static", path)

code_court/courthouse/templates/defendant/defendant_problem.html
{% extends "navbase.html" %}
{% block content %}
<h1>{{ problem.name }}</h1>
<br/>
<p>{{ markdown_statement }}</p>
<br/>
<h4>Sample Input:</h4>
<pre>{{ problem.sample_input }}</pre>
<br/>
<h4>Sample Output:</h4>
<pre>{{ problem.sample_output }}</pre>
<br/>

<script src="{{ url_for('main.send_static', path='codemirror-5.23.0/mode/python/python.js') }}"></script>
<script src="{{ url_for('main.send_static', path='codemirror-5.23.0/addon/display/placeholder.js') }}"></script>

<div class="panel panel-default">
    <form action="{{ url_for('defendant.problem', problem_id=problem.id) }}" method="POST" class="form">
        <div class="form-group panel-body">
            <textarea class="form-control" id="source_code" name="source_code">{% if source_code != None %}{{ source_code }}{% endif %}</textarea>
        </div>
        <div class="panel-footer">
          <button type="submit" name="action" value="submit" class="btn btn-default">Submit</button>
          <button type="submit" name="action" value="run" class="btn btn-default">Run</button>
        </div>
    </form>
</div>

<script>
    $(document).ready(function(){
        var editor = CodeMirror.fromTextArea(document.getElementById("source_code"),
        {lineNumbers: true, placeholder: "Enter source code here..."});
    });
</script>

{% endblock %}

code_court/courthouse/templates/defendant/index.html
{% extends "navbase.html" %}
{% block content %}
<h1>Defendant</h1>
<div>
  <ul>
    <a href="{{ url_for('defendant.submissions') }}" class="btn btn-info">See all submissions</a>
  </ul>
  <br/>
  {% for problem in problems %}
    <ul >
      <a href="{{ url_for('defendant.problem', problem_id=problem.id) }}" class="btn btn-default">
        {{ problem.name }}
      </a>
    </ul>
  {% endfor %}
</div>
{% endblock %}

code_court/courthouse/templates/defendant/problem.html
{% extends "navbase.html" %}
{% block content %}
<h1>{{ problem.name }}</h1>
<br/>
<p>{{ markdown_statement }}</p>
<br/>
<h4>Sample Input:</h4>
<pre>{{ problem.sample_input }}</pre>
<br/>
<h4>Sample Output:</h4>
<pre>{{ problem.sample_output }}</pre>
<br/>

<script src="{{ url_for('main.send_flask_static', path='codemirror-5.23.0/mode/python/python.js') }}"></script>
<script src="{{ url_for('main.send_flask_static', path='codemirror-5.23.0/addon/display/placeholder.js') }}"></script>

<div class="panel panel-default">
    <form action="{{ url_for('defendant.problem', problem_id=problem.id) }}" method="POST" class="form">
        <div class="form-group panel-body">
            <textarea class="form-control" id="source_code" name="source_code">{% if source_code != None %}{{ source_code }}{% endif %}</textarea>
        </div>
        <div class="panel-footer">
          <button type="submit" name="action" value="submit" class="btn btn-default">Submit</button>
          <button type="submit" name="action" value="run" class="btn btn-default">Run</button>
        </div>
    </form>
</div>

<script>
    $(document).ready(function(){
        var editor = CodeMirror.fromTextArea(document.getElementById("source_code"),
        {lineNumbers: true, placeholder: "Enter source code here..."});
    });
</script>

{% endblock %}

code_court/courthouse/templates/defendant/scoreboard.html
{% extends "navbase.html" %}
{% block content %}
<h2>Scoreboard</h2>
<table class="table">
    <thead>
        <tr>
            <th>name</th>
            {% for problem in problems %}
                <th>{{ problem.name }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.name }}</td>
            {% for problem in problems %}
                <td>
                    {% for run in scores[user.id][problem.id] %}
                        {% if run == RunState.passed %}
                            <span class="green">&#10003;</span>
                        {% elif run == RunState.failed %}
                            <span class="red">&#215;</span>
                        {% elif run == RunState.judging %}
                            <span>&#8635;</span>
                        {% endif %}
                    {% endfor %}
                </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

code_court/courthouse/templates/defendant/submissions.html
{% extends "navbase.html" %}
{% block content %}

<h1>Submissions</h1>
<div>
  <ul>
    <a href="{{ url_for('defendant.index') }}" class="btn btn-info">Back to problems</a>
  </ul>
  <br/>
  <table class="table">
      <thead>
          <tr>
              <th>Language</th>
              <th>Problem</th>
              <th>Submit_time</th>
              <th>Run_input</th>
              <th>Run_output</th>
              <th>is_passed</th>
              <th></th>
          </tr>
      </thead>
      <tbody>
          {% for submission in submissions %}
          <tr {% if submission.is_passed == True %}
                class="success"
              {% elif submission.is_passed == False %}
                class="danger"
              {% endif %}>
              <td class="run_name">{{ submission.language.name }}</td>
              <td class="run_problem">{{ submission.problem.name }}</td>
              <td class="run_submit_time">{{ submission.submit_time }}</td>
              <td class="run_run_input"><pre>{{ submission.run_input }}</pre></td>
              <td class="run_run_output">
                <pre>{% if submission.run_output != None %}{{ submission.run_output }}{% endif %}</pre>
              </td>
              <td class="run_is_passed">
                  {% if submission.is_passed == False %}
                      <span class="red">&#215;</span>
                  {% elif submission.is_passed == True %}
                      <span class="green">&#10003;</span>
                  {% else %}
                      <span>&#8635;</span>
                  {% endif %}
              </td>
          </tr>
          {% endfor %}
      </tbody>
  </table>
</div>



{% endblock %}