code_court/courthouse/views/auth.py
"""
Contains routes for handling authentication
"""
import util

from flask_login import login_user, logout_user
from sqlalchemy.orm.exc import NoResultFound

import model

from flask import abort, Blueprint, redirect, render_template, request, flash

auth = Blueprint("auth", __name__, template_folder="templates")


@auth.route("/login", methods=["GET"])
@util.ssl_required
def login_view():
    """general login page"""
    return render_template("auth/login.html")


@auth.route("/login", methods=["POST"])
@util.ssl_required
def login_submit():
    """processes login requests"""
    if "username" not in request.form:
        flash("username not found", "danger")
        abort(401)

    if "password" not in request.form:
        flash("Password not found", "danger")
        abort(401)

    username = request.form.get("username")
    password = request.form.get("password")

    try:
        user = model.User.query.filter_by(username=username).one()
    except NoResultFound as e:
        flash("Invalid username or password", "danger")
        abort(401)

    is_matching = user.verify_password(password)
    if is_matching:
        flash("Login successful", "success")
        login_user(user)
        return redirect("/admin")
    else:
        flash("Invalid username or password", "danger")
        abort(401)


@auth.route("/profile", methods=["GET"])
def profile():
    return render_template("auth/profile.html")


@auth.route("/logout", methods=["GET"])
def logout_submit():
    """processes logout requests"""
    logout_user()
    return redirect("/admin")

code_court/courthouse/views/defendant.py
import collections

from markdown import markdown
from enum import Enum

import util

import datetime

import model
from database import db_session

from flask_login import current_user
from flask import abort, Blueprint, current_app, render_template, request, Markup

defendant = Blueprint("defendant", __name__, template_folder="templates")


@defendant.route("/", methods=["GET"])
def index():
    """
    The index page for the defendant frontend

    Returns:
        a rendered defendant view template which shows all available problems
    """
    problems = model.Problem.query.all()

    return render_template("defendant/index.html", problems=problems)


RunState = Enum("RunState", "judging passed failed")


@defendant.route("/problem/<problem_id>/", methods=["GET"])
@defendant.route("/problem/<problem_id>/", methods=["POST"])
def problem(problem_id):
    problems = model.Problem.query.filter_by(id=problem_id).all()
    if len(problems) == 0:
        current_app.logger.info("Probelm %s doesn't exist", problem_id)
        abort(400)
    problem = problems[0]

    markdown_statement = Markup(markdown(problem.problem_statement))

    source_code = None
    if request.method == "POST":
        source_code = submit_code(problem)

    return render_template(
        "defendant/problem.html",
        problem=problem,
        markdown_statement=markdown_statement,
        source_code=source_code,
    )


@defendant.route("/submissions", methods=["GET"])
def submissions():
    submissions = model.Run.query.filter_by(
        user=current_user, is_submission=True
    ).order_by(
        model.Run.submit_time.desc()
    ).all()

    return render_template("defendant/submissions.html", submissions=submissions)


def submit_code(problem):
    """
    Creates a Run object and adds it to the database

    Args:
        problem: the problem source_code is being submitted to

    Returns:
        the submitted source_code as a string
    """
    source_code = request.form.get("source_code")
    if source_code is None:
        # TODO: give better feedback for failure
        current_app.logger.info("No source code given")
        abort(400)

    current_time = datetime.datetime.utcnow()

    # Hardcoded run details for the time being
    test_user = model.User.query.filter_by(username="testuser1").one()
    test_contest = model.Contest.query.filter_by(name="test_contest").one()
    python = model.Language.query.filter_by(name="python").one()

    button_action = request.form.get("action")
    is_submission = button_action == "submit" and not button_action == "run"

    run = model.Run(
        test_user,
        test_contest,
        python,
        problem,
        current_time,
        source_code,
        problem.secret_input,
        problem.secret_output,
        is_submission,
    )

    db_session.add(run)
    db_session.commit()

    return source_code

code_court/courthouse/views/main.py
from flask import Blueprint, send_from_directory

main = Blueprint("main", __name__, template_folder="templates")


@main.route("/flaskstatic/<path:path>")
def send_flask_static(path):
    return send_from_directory("static", path)

code_court/courthouse/templates/401.html
{% extends "navbase.html" %}

{% block content %}
<h1>Unauthorized</h1>
{% endblock %}

code_court/courthouse/templates/admin_index.html
{% extends "navbase.html" %}
{% block content %}
<h1>Admin</h1>
<ul>
	<li><a href="{{ url_for("configurations.configurations_view") }}">configurations</a>
		<li><a href="{{ url_for("clarifications.clarifications_view")}}">clarifications</a>
    <li><a href="{{ url_for("languages.languages_view") }}">languages</a>
    <li><a href="{{ url_for("problems.problems_view") }}">problems</a>
    <li><a href="{{ url_for("users.users_view") }}">users</a>
    <li><a href="{{ url_for("runs.runs_view") }}">runs</a>
    <li><a href="{{ url_for("contests.contests_view") }}">contests</a>
</ul>

<h1>Utils</h1>
<ul>
    <li><a href="{{ url_for("utils.random_contestants") }}">random contestants</a>
    <li><a href="{{ url_for("utils.invalidate_caches") }}">invalidate caches</a>
</ul>

<h1>Info</h2>
<table class="table">
    <tbody>
        {% for key, val in info.items() %}
        <tr>
            <td><strong>{{ key }}</strong></td>
            <td>{{ val }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

code_court/courthouse/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Ben Doan">
        <link rel="icon" type="image/png" href="{{ url_for('main.send_flask_static', path='img/gavel-16x16.png') }}?1">

        <title>code_court</title>

        <script src="{{ url_for('main.send_flask_static', path='js/jquery-2.2.4.min.js') }}"></script>
        <script src="{{ url_for('main.send_flask_static', path='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('main.send_flask_static', path='codemirror-5.23.0/codemirror.js') }}"></script>
        <script src="{{ url_for('main.send_flask_static', path='js-webshim/minified/polyfiller.js') }}"></script>
        <script>
            webshim.polyfill('forms-ext');
        </script>

        <link href="{{ url_for('main.send_flask_static', path='codemirror-5.23.0/codemirror.css') }}" rel="stylesheet">
        <link href="{{ url_for('main.send_flask_static', path='css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('main.send_flask_static', path='css/main.css') }}" rel="stylesheet">
    </head>

    <body>
        {% block page %}
        <p>content should be here</p>
        {% endblock %}
    </body>
</html>

code_court/courthouse/templates/index.html
{% extends "navbase.html" %}

{% block content %}
    <pre style="font-size:25pt;background-color:#fff; border:none; line-height:24pt;">
               _                              _
  ___ ___   __| | ___     ___ ___  _   _ _ __| |_
 / __/ _ \ / _` |/ _ \   / __/ _ \| | | | '__| __|
| (_| (_) | (_| |  __/  | (_| (_) | |_| | |  | |_
 \___\___/ \__,_|\___|___\___\___/ \__,_|_|   \__|
                    |_____|

    </pre>
{% endblock %}

code_court/courthouse/templates/message.html
{% extends "navbase.html" %}

{% block content %}
{{message}}
{% endblock %}

code_court/courthouse/templates/navbase.html
{% extends "base.html" %}

{% block page %}
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/admin">
                <span><img height="32" width="32" src="{{ url_for('main.send_flask_static', path='img/gavel-32x32.png') }}" class="" /></span>
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% if "operator" in current_user.user_roles %}
                <li {% if request.path.startswith('/admin') %}class="active"{% endif %}>
                    <a href="{{ url_for('admin.index') }}">Admin</a>
                </li>
                {% endif %}

                {% if "defendant" in current_user.user_roles %}
                <li {% if request.path == '/defendant' %}class="active"{% endif %}>
                    <a href="{{ url_for('defendant.index') }}">Defendant</a>
                </li>
                {% endif %}
            </ul>
            <span class="navbar-right">
                {% if current_user.username %}
                    <p class="navbar-text">logged in as <strong><a href="/profile">{{ current_user.username }}</strong></a></p>
                    <a href="{{ url_for('auth.logout_submit') }}" class="btn btn-default navbar-btn btn-xs">Log out</a>
                {% else %}
                    <a href="{{ url_for('auth.login_submit') }}" class="btn btn-default navbar-btn btn-xs">Log in</a>
                {% endif %}
            </span>
        </div>
    </div>
</nav>
<div class="container" id="content">
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            <div class="messages">
                {% for category, message in messages %}
                    {% if category == "message" %}
                        {% set category = "info" %}
                    {% endif %}
                    <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}

    {% block content %}
    <p>content should be here</p>
    {% endblock %}
</div>
<div class="container" id="footer">
    <footer>
    </footer>
</div>
{% endblock %}

code_court/courthouse/templates/pagination.html
{% macro render(endpoint, pagination, request='') %}
<nav>
<ul class="pagination">
{%- for page in pagination.iter_pages(left_edge=1, left_current=2, right_current=3, right_edge=1) %}
{% if page %}
    {% if page == pagination.page %}
    <li class="active"><a href="{{ url_for(endpoint, page=page) }}">{{ page }}</a></li>
    {% else %}
    <li><a href="{{ url_for(endpoint, page=page) + request }}">{{ page }}</a></li>
    {% endif %}
{% else %}
<li class="disabled"><a href='#'>...</a></li>
{% endif %}
{%- endfor %}
</ul>
</nav>
{% endmacro %}

code_court/courthouse/templates/viewbase.html
{% extends "navbase.html" %}

{% block content %}

{% block view %}
<p>view should be here</p>
{% endblock %}

<div class="modal fade" tabindex="-1" role="dialog" id="confirm">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Confirm Delete</h4>
            <div>
            <div class="modal-body">
                This action cannot be undone.
            </div
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-danger btn-sm" id="delete">Delete</button>
                <button type="button" data-dismiss="modal" class="btn btn-sm">Cancel</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('button[id="del"]').on('click', function(e) {
        var $form = $(this).closest('form');
        e.preventDefault();
        $('#confirm').modal({
                backdrop: 'static',
                keyboard: false
            })
        .on('click', '#delete', function(e) {
            $form.trigger('submit');
        });
    });
</script>

{% endblock %}